### ISSUE TITLE
Fix crash on logout

### ISSUE THREAD

**Issue by yostyle** [tchapgouv/tchap-android-v2#191]
Sometimes the app crash on logout.

```
2021-09-08 17:08:40.897 4701-4729/? E/Watchdog: !@Sync: 2658 heap: 72 / 77 [2021-09-08 17:08:40.897] sdogWay: softdog
2021-09-08 17:10:43.774 30065-30065/fr.gouv.tchap.a E/DecorView: mWindow.mActivityCurrentConfig is null
2021-09-08 17:10:43.774 30065-30065/fr.gouv.tchap.a E/DecorView: mWindow.mActivityCurrentConfig is null
2021-09-08 17:10:43.774 30065-30065/fr.gouv.tchap.a E/DecorView: mWindow.mActivityCurrentConfig is null
2021-09-08 17:10:44.926 30065-30065/fr.gouv.tchap.a E/ViewRootImpl: sendUserActionEvent() mView returned.
2021-09-08 17:10:44.926 30065-30065/fr.gouv.tchap.a E/ViewRootImpl: sendUserActionEvent() mView returned.
2021-09-08 17:10:44.926 30065-30065/fr.gouv.tchap.a E/ViewRootImpl: sendUserActionEvent() mView returned.
2021-09-08 17:10:46.183 30065-31334/fr.gouv.tchap.a E/DefaultDownloadKeysForUsers: Exception when executing request
2021-09-08 17:10:46.183 30065-31334/fr.gouv.tchap.a E/DefaultDownloadKeysForUsers: Exception when executing request
2021-09-08 17:10:46.183 30065-30065/fr.gouv.tchap.a E/CleanupSession: All realm instance for session has not been closed (3)
2021-09-08 17:10:46.183 30065-30065/fr.gouv.tchap.a E/CleanupSession: All realm instance for session has not been closed (3)
2021-09-08 17:10:46.186 30065-31334/fr.gouv.tchap.a E/DeviceListManager: ## CRYPTO | doKeyDownloadForUsers(): error
2021-09-08 17:10:46.186 30065-31334/fr.gouv.tchap.a E/DeviceListManager: ## CRYPTO | doKeyDownloadForUsers(): error
2021-09-08 17:10:46.190 30065-31334/fr.gouv.tchap.a E/DeviceListManager: ## CRYPTO | refreshOutdatedDeviceLists() : ERROR updating device keys for users [@yoan.pintas-matrix.org:agent.dinum.tchap.gouv.fr]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-09-08 17:10:46.190 30065-31334/fr.gouv.tchap.a E/DeviceListManager: ## CRYPTO | refreshOutdatedDeviceLists() : ERROR updating device keys for users [@yoan.pintas-matrix.org:agent.dinum.tchap.gouv.fr]
2021-09-08 17:10:46.233 30065-31707/fr.gouv.tchap.a V/FileUtilsKt: deleteFile: /data/user/0/fr.gouv.tchap.a/cache/logs/logs.0.txt
2021-09-08 17:10:46.183 30065-31334/fr.gouv.tchap.a E/DefaultDownloadKeysForUsers: Exception when executing request
2021-09-08 17:10:46.183 30065-30065/fr.gouv.tchap.a E/CleanupSession: All realm instance for session has not been closed (3)
2021-09-08 17:10:46.235 30065-31583/fr.gouv.tchap.a E/AndroidRuntime: FATAL EXCEPTION: pool-18-thread-1
    Process: fr.gouv.tchap.a, PID: 30065
2021-09-08 17:10:46.235 30065-31583/fr.gouv.tchap.a E/AndroidRuntime: FATAL EXCEPTION: pool-18-thread-1
    Process: fr.gouv.tchap.a, PID: 30065
2021-09-08 17:10:46.186 30065-31334/fr.gouv.tchap.a E/DeviceListManager: ## CRYPTO | doKeyDownloadForUsers(): error
    java.util.concurrent.CancellationException: Closing crypto module
    io.realm.exceptions.RealmFileException: Directory at path '/data/user/0/fr.gouv.tchap.a/files/a6d56d9bfc495f2b00c77dda4253cb80/crypto_store.realm.lock' does not exist. (open("/data/user/0/fr.gouv.tchap.a/files/a6d56d9bfc495f2b00c77dda4253cb80/crypto_store.realm.lock") failed: No such file or directory Path: /data/user/0/fr.gouv.tchap.a/files/a6d56d9bfc495f2b00c77dda4253cb80/crypto_store.realm.lock
    Exception backtrace:
        at org.matrix.android.sdk.internal.crypto.DefaultCryptoService$close$1.invokeSuspend(DefaultCryptoService.kt:391)
    io.realm.exceptions.RealmFileException: Directory at path '/data/user/0/fr.gouv.tchap.a/files/a6d56d9bfc495f2b00c77dda4253cb80/crypto_store.realm.lock' does not exist. (open("/data/user/0/fr.gouv.tchap.a/files/a6d56d9bfc495f2b00c77dda4253cb80/crypto_store.realm.lock") failed: No such file or directory Path: /data/user/0/fr.gouv.tchap.a/files/a6d56d9bfc495f2b00c77dda4253cb80/crypto_store.realm.lock
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/user/0/fr.gouv.tchap.a/files/a6d56d9bfc495f2b00c77dda4253cb80/crypto_store.realm.lock) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: NOT_FOUND.
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
    <backtrace not supported on this platform>) (/data/user/0/fr.gouv.tchap.a/files/a6d56d9bfc495f2b00c77dda4253cb80/crypto_store.realm.lock) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: NOT_FOUND.
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
        at android.os.Looper.loop(Looper.java:237)
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
        at io.realm.BaseRealm.<init>(BaseRealm.java:141)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
        at io.realm.BaseRealm.<init>(BaseRealm.java:108)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:422)
        at com.zhuinden.monarchy.Monarchy.doWithRealm(Monarchy.java:317)
        at io.realm.Realm.getInstance(Realm.java:424)
2021-09-08 17:10:46.190 30065-31334/fr.gouv.tchap.a E/DeviceListManager: ## CRYPTO | refreshOutdatedDeviceLists() : ERROR updating device keys for users [@yoan.pintas-matrix.org:agent.dinum.tchap.gouv.fr]
        at com.zhuinden.monarchy.Monarchy.runTransactionSync(Monarchy.java:164)
        at com.zhuinden.monarchy.Monarchy.doWithRealm(Monarchy.java:317)
    java.util.concurrent.CancellationException: Closing crypto module
        at com.zhuinden.monarchy.Monarchy$8.run(Monarchy.java:335)
        at com.zhuinden.monarchy.Monarchy.runTransactionSync(Monarchy.java:164)
        at org.matrix.android.sdk.internal.crypto.DefaultCryptoService$close$1.invokeSuspend(DefaultCryptoService.kt:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at com.zhuinden.monarchy.Monarchy$8.run(Monarchy.java:335)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.lang.Thread.run(Thread.java:919)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at android.os.Handler.handleCallback(Handler.java:883)
        at java.lang.Thread.run(Thread.java:919)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
    <backtrace not supported on this platform>) (/data/user/0/fr.gouv.tchap.a/files/a6d56d9bfc495f2b00c77dda4253cb80/crypto_store.realm.lock) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: NOT_FOUND.
2021-09-08 17:10:46.245 30065-31583/fr.gouv.tchap.a E/VectorUncaughtExceptionHandler: FATAL EXCEPTION Element Build : 209256032
2021-09-08 17:10:46.245 30065-31583/fr.gouv.tchap.a E/VectorUncaughtExceptionHandler: FATAL EXCEPTION Element Build : 209256032
2021-09-08 17:10:46.235 30065-31583/fr.gouv.tchap.a E/AndroidRuntime: FATAL EXCEPTION: pool-18-thread-1
2021-09-08 17:10:46.245 30065-31583/fr.gouv.tchap.a E/VectorUncaughtExceptionHandler: FATAL EXCEPTION Element Build : 209256032

```

**Comment by giomfo** [comment]
dup #194
