### ISSUE TITLE
After external reset password and a reset of data -> blocked on splashscreen

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android-v2#441]
How to reproduce : 
- Reset password on another device
- The app show : 
![image](https://user-images.githubusercontent.com/1238254/154736208-70de0901-59a2-4396-affe-014b857f3e9d.png)
- I choose "clear all data" and validate
![image](https://user-images.githubusercontent.com/1238254/154736109-b1ddf6e3-12a2-4498-86db-92c22b2a08f5.png)
- The app restart and block on this screen
![image](https://user-images.githubusercontent.com/1238254/154736004-9b6fdb5e-23d0-4518-91af-67f676dc465d.png)

Adb logcat result : 
```
02-18 18:46:41.153  1260  1888 I WindowManager: Screen frozen for +744ms due to Window{2b0bb4c u0 fr.gouv.tchap.a/im.vector.app.features.signout.soft.SoftLogoutActivity}
02-18 18:47:32.025  1260  1891 I ActivityManager: START u0 {flg=0x10008000 cmp=fr.gouv.tchap.a/im.vector.app.features.MainActivity (has extras)} from uid 10403

02-18 18:50:30.586  3957 24889 W Bundle  : Key android.icon expected Parcelable but value was a java.lang.Integer.  The default value <null> was returned.
02-18 18:50:30.586  3957 24889 W Bundle  : Attempt to cast generated internal exception:
02-18 18:50:30.586  3957 24889 W Bundle  : java.lang.ClassCastException: java.lang.Integer cannot be cast to android.os.Parcelable
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.os.Bundle.getParcelable(Bundle.java:946)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.app.Notification.fixDuplicateExtra(Notification.java:2780)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.app.Notification.fixDuplicateExtras(Notification.java:2770)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.app.Notification.readFromParcelImpl(Notification.java:2176)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.app.Notification.<init>(Notification.java:2104)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.app.Notification$1.createFromParcel(Notification.java:2656)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.app.Notification$1.createFromParcel(Notification.java:2653)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.os.Parcel.readParcelable(Parcel.java:2818)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.view.accessibility.AccessibilityEvent.readAccessibilityRecordFromParcel(AccessibilityEvent.java:1232)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.view.accessibility.AccessibilityEvent.initFromParcel(AccessibilityEvent.java:1182)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.view.accessibility.AccessibilityEvent$1.createFromParcel(AccessibilityEvent.java:1426)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.view.accessibility.AccessibilityEvent$1.createFromParcel(AccessibilityEvent.java:1423)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.accessibilityservice.IAccessibilityServiceClient$Stub.onTransact(IAccessibilityServiceClient.java:68)
02-18 18:50:30.586  3957 24889 W Bundle  : 	at android.os.Binder.execTransact(Binder.java:731)
02-18 18:50:31.546   933   933 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
02-18 18:50:41.564   933   933 I chatty  : uid=1000(system) composer@2.1-se identical 10 lines
02-18 18:50:41.812   933   933 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
02-18 18:50:42.671   796   813 W Netd    : No subsystem found in netlink event
02-18 18:50:43.574   933   933 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
02-18 18:50:43.592   933   933 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
02-18 18:50:44.110  8872  8872 D R:Battery: Battery changed: Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) } @ 47615609
02-18 18:50:44.111   925  1180 D audio_hw_primary: adev_set_parameters: enter: wireless_charging=off
02-18 18:50:44.111   925  1180 D audio_hw_extn: audio_extn_set_anc_parameters: anc_enabled:0
02-18 18:50:44.221   953  2240 V LocSvc_HIDL_IzatProvider: [onLocationChanged][71] [HS] =>>>> [HC]
02-18 18:50:44.221  1260  1931 I chatty  : uid=1000(system) HwBinder:1260_3 expire 1 line
02-18 18:50:44.596   933   933 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
02-18 18:50:44.613   933   933 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
02-18 18:50:45.621  1260  4073 I chatty  : uid=1000(system) Binder:1260_11 expire 2 lines
02-18 18:50:45.965   756   756 I QNS     : QNS: soc=54, v=4024, i=1275, t=322
02-18 18:50:45.965   756   756 I QNS     : QNS: requested charging params: current: 2075, voltage: 4350
02-18 18:50:46.627  3957 24889 W Bundle  : Key android.icon expected Parcelable but value was a java.lang.Integer.  The default value <null> was returned.
02-18 18:50:46.628  3957 24889 W Bundle  : Attempt to cast generated internal exception:
02-18 18:50:46.628  3957 24889 W Bundle  : java.lang.ClassCastException: java.lang.Integer cannot be cast to android.os.Parcelable
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.os.Bundle.getParcelable(Bundle.java:946)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.app.Notification.fixDuplicateExtra(Notification.java:2780)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.app.Notification.fixDuplicateExtras(Notification.java:2770)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.app.Notification.readFromParcelImpl(Notification.java:2176)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.app.Notification.<init>(Notification.java:2104)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.app.Notification$1.createFromParcel(Notification.java:2656)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.app.Notification$1.createFromParcel(Notification.java:2653)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.os.Parcel.readParcelable(Parcel.java:2818)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.view.accessibility.AccessibilityEvent.readAccessibilityRecordFromParcel(AccessibilityEvent.java:1232)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.view.accessibility.AccessibilityEvent.initFromParcel(AccessibilityEvent.java:1182)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.view.accessibility.AccessibilityEvent$1.createFromParcel(AccessibilityEvent.java:1426)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.view.accessibility.AccessibilityEvent$1.createFromParcel(AccessibilityEvent.java:1423)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.accessibilityservice.IAccessibilityServiceClient$Stub.onTransact(IAccessibilityServiceClient.java:68)
02-18 18:50:46.628  3957 24889 W Bundle  : 	at android.os.Binder.execTransact(Binder.java:731)
02-18 18:50:48.585   933 26994 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
```

**Comment by jdauphant** [comment]
If I kill the app and restart, it's the splashscreen isn't blocked anymore

**Comment by giomfo** [comment]
dup https://github.com/tchapgouv/tchap-android-v2/issues/397
