### ISSUE TITLE
Crash on back 2.0.1

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android-v2#466]
"j'ai fait un retour arrière et plantage"

```
crash call stack ---------------------------------
Element Build : 40200012
Element Version : 2.0.1-dev [40200012] (F-002ed84d-2022-02-23 16:28:22 +0100)
SDK Version : 1.3.12 (002ed84d)
Phone : Core-X4 NEO (2022022410 11 REL)
Memory statuses
usedSize 22 MB
freeSize 19 MB
totalSize 42 MB
Thread: Crypto_Thread, Exception: java.lang.NullPointerException
at org.matrix.android.sdk.internal.crypto.MXOlmDevice.addInboundGroupSession(MXOlmDevice.kt:5)
at org.matrix.android.sdk.internal.crypto.algorithms.megolm.MXMegolmDecryption.onRoomKeyEvent(MXMegolmDecryption.kt:77)
at org.matrix.android.sdk.internal.crypto.DefaultCryptoService$onToDeviceEvent$1.invokeSuspend(DefaultCryptoService.kt:176)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.os.HandlerThread.run(HandlerThread.java:67)

User-Agent: "Tchap/2.0.1-dev (Linux; U; Android 11; Core-X4 NEO __REDACTED__; Flavour FDroid; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.1-dev [40200012] (F-002ed84d-2022-02-23 16:28:22 +0100)"
app_language: "fr_FR"
branch_name: "HEAD"
can_contact: "false"
default_app_language: "fr_FR"
device: "Core-X4 NEO"
device_id: "__REDACTED__"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (002ed84d)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30) 2022022410-REL"
server_version: "undefined"
theme: "system"
user_id: "__REDACTED__"
verbose_log: "OFF"
```

**Comment by Claire1817** [comment]
Issue opened on Element: https://github.com/vector-im/element-android/issues/3601

**Comment by giomfo** [comment]
cannot reproduce
