### ISSUE TITLE
Crash after sending a message

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-android-v2#469]
C'est moi qui ai eu le pb 

tchap-android] [Element] crash après avoir envoyé un message

User message:

[Element] crash après avoir envoyé un message
 crash call stack ---------------------------------
Element Build : 40200011
Element Version : 2.0.1 [40200011] (G-002ed84d-2022-02-23 16:28:22 +0100)
SDK Version : 1.3.12 (002ed84d)
Phone : SM-J330FN (J330FNXXS4CUD3 9 REL)
Memory statuses
usedSize 67 MB
freeSize 3 MB
totalSize 70 MB
Thread: main, Exception: java.lang.IllegalArgumentException: Max number of dynamic shortcuts exceeded
at android.os.Parcel.createException(Parcel.java:1970)
at android.os.Parcel.readException(Parcel.java:1934)
at android.os.Parcel.readException(Parcel.java:1884)
at android.content.pm.IShortcutService$Stub$Proxy.addDynamicShortcuts(IShortcutService.java:595)
at android.content.pm.ShortcutManager.addDynamicShortcuts(ShortcutManager.java:396)
at im.vector.app.features.home.ShortcutsHandler.createShortcuts(ShortcutsHandler.kt:34)
at im.vector.app.features.home.ShortcutsHandler.access$createShortcuts(ShortcutsHandler.kt:1)
at im.vector.app.features.home.ShortcutsHandler$observeRoomsAndBuildShortcuts$4.invokeSuspend(ShortcutsHandler.kt:8)
at im.vector.app.features.home.ShortcutsHandler$observeRoomsAndBuildShortcuts$4.invoke(Unknown Source:8)
at im.vector.app.features.home.ShortcutsHandler$observeRoomsAndBuildShortcuts$4.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:6)
at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:1)
at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:25)
at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
at androidx.lifecycle.FlowLiveDataConversions$asFlow$1.invokeSuspend(FlowLiveData.kt:11)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.pm.ShortcutService.enforceMaxActivityShortcuts(ShortcutService.java:1729)
at com.android.server.pm.ShortcutPackage.enforceShortcutCountsBeforeOperation(ShortcutPackage.java:1104)
at com.android.server.pm.ShortcutService.addDynamicShortcuts(ShortcutService.java:2017)
at android.content.pm.IShortcutService$Stub.onTransact(IShortcutService.java:119)
at android.os.Binder.execTransact(Binder.java:739)

User-Agent: "Tchap/2.0.1 (Linux; U; Android 9; SM-J330FN Build/PPR1.180610.01; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.1 [40200011] (G-002ed84d-2022-02-23 16:28:22 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-J330FN"
device_id: "QZCEDPBAMD"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (002ed84d)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "9 (API 28) J330FNXXS4CUD3-REL"
server_version: "undefined"
theme: "light"
user_id: "@juliette.dixmier-beta.gouv.fr:agent.dinum.tchap.gouv.fr"
verbose_log: "OFF"

**Comment by Claire1817** [comment]
i didn't reproduce the crash.
After discussing with Juliette, she didn't reproduce the bug either.

**Comment by giomfo** [comment]
cannot reproduce

**Comment by Delphgateau** [comment]
+1
Ticket crisp : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_d3bc4d1c-4aaf-4a71-a941-16a426694629/

Thread: main, Exception: java.lang.IllegalArgumentException: Max number of dynamic shortcuts exceeded
at android.os.Parcel.createException(Parcel.java:1970)
at android.os.Parcel.readException(Parcel.java:1934)
at android.os.Parcel.readException(Parcel.java:1884)
at android.content.pm.IShortcutService$Stub$Proxy.addDynamicShortcuts(IShortcutService.java:595)
at android.content.pm.ShortcutManager.addDynamicShortcuts(ShortcutManager.java:396)
at androidx.core.content.pm.ShortcutManagerCompat.pushDynamicShortcut(ShortcutManagerCompat.java:21)
at im.vector.app.features.home.ShortcutsHandler.createShortcuts(ShortcutsHandler.kt:10)
at im.vector.app.features.home.ShortcutsHandler.access$createShortcuts(Unknown Source:0)
at im.vector.app.features.home.ShortcutsHandler$observeRoomsAndBuildShortcuts$5.invokeSuspend(ShortcutsHandler.kt:9)
at im.vector.app.features.home.ShortcutsHandler$observeRoomsAndBuildShortcuts$5.invoke(Unknown Source:8)
at im.vector.app.features.home.ShortcutsHandler$observeRoomsAndBuildShortcuts$5.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:6)
at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:1)
at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:25)
at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
at androidx.lifecycle.FlowLiveDataConversions$asFlow$1.invokeSuspend(FlowLiveData.kt:11)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1524d85, Dispatchers.Main.immediate]
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.pm.ShortcutService.enforceMaxActivityShortcuts(ShortcutService.java:1692)
at com.android.server.pm.ShortcutPackage.enforceShortcutCountsBeforeOperation(ShortcutPackage.java:1104)
at com.android.server.pm.ShortcutService.addDynamicShortcuts(ShortcutService.java:1980)
at android.content.pm.IShortcutService$Stub.onTransact(IShortcutService.java:119)
at android.os.Binder.execTransact(Binder.java:739)

**Comment by Delphgateau** [comment]
+1
Thread: main, Exception: java.lang.IllegalArgumentException: Max number of dynamic shortcuts exceeded
at android.os.Parcel.readException(Parcel.java:1971)
at android.os.Parcel.readException(Parcel.java:1913)
at android.content.pm.IShortcutService$Stub$Proxy.addDynamicShortcuts(IShortcutService.java:563)
at android.content.pm.ShortcutManager.addDynamicShortcuts(ShortcutManager.java:682)
at androidx.core.content.pm.ShortcutManagerCompat.pushDynamicShortcut(ShortcutManagerCompat.java:21)
at im.vector.app.features.home.ShortcutsHandler.createShortcuts(ShortcutsHandler.kt:10)
at im.vector.app.features.home.ShortcutsHandler.access$createShortcuts(Unknown Source:0)
at im.vector.app.features.home.ShortcutsHandler$observeRoomsAndBuildShortcuts$5.invokeSuspend(ShortcutsHandler.kt:9)
at im.vector.app.features.home.ShortcutsHandler$observeRoomsAndBuildShortcuts$5.invoke(Unknown Source:8)
at im.vector.app.features.home.ShortcutsHandler$observeRoomsAndBuildShortcuts$5.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:6)
at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:1)
at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:25)
at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
at androidx.lifecycle.FlowLiveDataConversions$asFlow$1.invokeSuspend(FlowLiveData.kt:11)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b63aff8, Dispatchers.Main.immediate]

User-Agent: "Tchap/2.5.2 (samsung SM-A520F; Android 8.0.0; R16NW.A520FXXUGCTKA; Flavour GooglePlay; MatrixAndroidSdk2 1.5.2)"
Version: "2.5.2 [402050202] (G-d616bb1b-2022-12-27 17:34:57 +0100)"
default_app_language: "fr_FR"
device: "SM-A520F"
locale: "fr_FR"
matrix_sdk_version: "1.5.2 (d616bb1b)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "8.0.0 (API 26) A520FXXUGCTKA-REL"
server_version: "undefined"
theme: "light"
