### ISSUE TITLE
Crash on logout

### ISSUE THREAD

**Issue by Florian14** [tchapgouv/tchap-android-v2#478]
The application systematically crashes in the develop branch (version 2.1.0-dev [40201001] (G-d3c11ebd).

It has been potentially fixed in Element after the 1.4.2 version.

Here is the stacktrace:

```
2022-03-09 17:49:10.836 4686-5324/fr.gouv.tchap.dev E/AndroidRuntime: FATAL EXCEPTION: pool-22-thread-3
    Process: fr.gouv.tchap.dev, PID: 4686
    java.lang.IllegalStateException: This method can only be called on the main thread!
        at com.zhuinden.monarchy.Monarchy.assertMainThread(Monarchy.java:174)
        at com.zhuinden.monarchy.Monarchy.findAllMappedWithChanges(Monarchy.java:444)
        at org.matrix.android.sdk.internal.session.user.accountdata.UserAccountDataDataSource.getLiveAccountDataEvents(UserAccountDataDataSource.kt:55)
        at org.matrix.android.sdk.internal.session.user.accountdata.DefaultSessionAccountDataService.getLiveUserAccountDataEvents(DefaultSessionAccountDataService.kt:56)
        at org.matrix.android.sdk.flow.FlowSession.liveUserAccountData(FlowSession.kt:149)
        at im.vector.app.features.workers.signout.SignoutCheckViewModel.init(SignoutCheckViewModel.kt:100)
        at im.vector.app.features.workers.signout.SignoutCheckViewModel$1.invoke(SignoutCheckViewModel.kt:79)
        at im.vector.app.features.workers.signout.SignoutCheckViewModel$1.invoke(SignoutCheckViewModel.kt:77)
        at com.airbnb.mvrx.CoroutinesStateStore$flushQueuesOnce$2$2.invokeSuspend(CoroutinesStateStore.kt:91)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by Claire1817** [comment]
Issue opened on Element: https://github.com/vector-im/element-android/issues/3601

**Comment by Florian14** [comment]
@Claire1817 did you mention the right issue? The stacktrace is different and I don't see any relation with the logout?

**Comment by giomfo** [comment]
@Florian14 can you please try to reproduce?

**Comment by giomfo** [comment]
cannot reproduce
