### ISSUE TITLE
Crash redémarrage intempestif 

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android-v2#504]
crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : Mi 9T Pro (V12.5.1.0.RFKEUXM 11 REL)
Memory statuses
usedSize 13 MB
freeSize 12 MB
totalSize 26 MB
Thread: main, Exception: NetworkConnection(ioException=java.net.SocketTimeoutException: timeout)
at org.matrix.android.sdk.internal.session.identity.DefaultIdentityRegisterTask.execute(IdentityRegisterTask.kt:32)
at org.matrix.android.sdk.internal.session.identity.DefaultIdentityRegisterTask$execute$1.invokeSuspend(Unknown Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:17)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:8061)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:656)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.net.SocketTimeoutException: timeout
at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:1)
at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:8)
at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:15)
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:2)
at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:1)
at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:2)
at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:1)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:40)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:30)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:37)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:36)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at org.matrix.android.sdk.internal.network.ApiInterceptor.intercept(ApiInterceptor.kt:8)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor..kt:57)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at org.matrix.android.sdk.internal.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:29)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at org.matrix.android.sdk.internal.network.TimeOutInterceptor.intercept(TimeOutInterceptor.kt:33)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain..kt:14)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:23)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:12)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.net.SocketException: Socket closed
at java.net.SocketInputStream.read(SocketInputStream.java:209)
at java.net.SocketInputStream.read(SocketInputStream.java:144)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
at okio.InputStreamSource.read(JvmOkio.kt:5)
at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:3)
... 28 more

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; Mi 9T Pro Build/RKQ1.200826..00; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "Mi 9T Pro"
device_id: "KZVMCDQOVH"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30) V12.5.1.0.RFKEUXM-REL"
server_version: "undefined"
theme: "system"

**Comment by Claire1817** [comment]
we don't find the stacktrace in google play console.
