### ISSUE TITLE
Crash ouverture d'une discussion Exception: com.airbnb.epoxy.IllegalEpoxyUsage

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android-v2#505]
crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : M2102K1C (V13.0.9.0.SKACNXM 12 REL)
Memory statuses
usedSize 20 MB
freeSize 15 MB
totalSize 36 MB
Thread: Timeline_Building_Thread, Exception: com.airbnb.epoxy.IllegalEpoxyUsage: You must set an id on a model before adding it. Use the @AutoModel annotation if you want an id to be automatically generated for you.
at com.airbnb.epoxy.EpoxyController.addInternal(EpoxyController.java:8)
at com.airbnb.epoxy.EpoxyModel.addTo(EpoxyModel.java:1)
at com.airbnb.epoxy.EpoxyController.add(EpoxyController.java:1)
at com.airbnb.epoxy.EpoxyController.add(EpoxyController.java:7)
at im.vector.app.features.home.room.detail.timeline.TimelineEventController.buildModels(TimelineEventController.kt:10)
at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:6)
at android.os.Handler.handleCallback(Unknown Source:2)
at android.os.Handler.dispatchMessage(Unknown Source:4)
at android.os.Looper.loopOnce(Unknown Source:176)
at android.os.Looper.loop(Unknown Source:76)
at android.os.HandlerThread.run(Unknown Source:28)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 12; M2102K1C Build/SKQ1.211006.00; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "true"
default_app_language: "fr_FR"
device: "M2102K1C"
device_id: "FSBWKIZCGS"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "12 (API 31) V13.0.9.0.SKACNXM-REL"
server_version: "undefined"
theme: "light"

**Comment by Claire1817** [comment]
found on Element: https://github.com/vector-im/element-android/issues/3393

**Comment by Claire1817** [comment]
We don't find the stacktrace in the playstore console.
