### ISSUE TITLE
Crash sans raison apparente - Exception: java.lang.IllegalArgument

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-android-v2#506]
crash call stack ---------------------------------
Element Build : 40200031
Element Version : 2.0.3 [40200031] (G-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : SM-A015F (A015FXXS5BUL1 11 REL)
Memory statuses
usedSize 20 MB
freeSize 11 MB
totalSize 32 MB
Thread: main, Exception: java.lang.IllegalArgumentException: PrecomputedText's Parameters don't match the parameters of this TextView.Consider using setTextMetricsParams(precomputedText.getParams()) to override the settings of this TextView: PrecomputedText: {textSize=28.0, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[fr_FR], typeface=android.graphics.Typeface@724deb19, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@68112e6, breakStrategy=1, hyphenationFrequency=0}TextView: {textSize=88.0, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[fr_FR], typeface=android.graphics.Typeface@724deb19, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@68112e6, breakStrategy=1, hyphenationFrequency=0}
at android.widget.TextView.setText(TextView.java:6844)
at android.widget.TextView.setText(TextView.java:6761)
at android.widget.TextView.setText(TextView.java:6713)
at androidx.core.widget.TextViewCompat.setPrecomputedText(TextViewCompat.java:4)
at androidx.appcompat.widget.AppCompatTextView.consumeTextFutureAndSetBlocking(AppCompatTextView.java:3)
at androidx.appcompat.widget.AppCompatTextView.getText(AppCompatTextView.java:1)
at androidx.emoji2.viewsintegration.EmojiInputFilter.filter(EmojiInputFilter.java:4)
at android.widget.TextView.setText(TextView.java:6797)
at android.widget.TextView.setText(TextView.java:6761)
at android.widget.TextView.setText(TextView.java:6713)
at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind(MessageTextItem.kt:44)
at im.vector.app.features.home.room.detail.timeline.item.MessageTextItem.bind(MessageTextItem.kt:6)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:25)
at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:3)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:7)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:131)
at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:7)
at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:28)
at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:13)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8633)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; SM-A015F Build/RP1A.200720.01; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200031] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-A015F"
device_id: "NIHOBJEFYA"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30) A015FXXS5BUL1-REL"
server_version: "undefined"
theme: "light"

**Comment by Claire1817** [comment]
It comes from Emoji

**Comment by Claire1817** [comment]
We don't find the stacktrace in the playstore console.
