### ISSUE TITLE
Crash - crash de l'application Exception: java.lang.StringIndexOutOfBoundsException: length=161; index=-1 at java.lang.String.substring(String.java:2057)

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-android-v2#530]
crash call stack ---------------------------------
Element Build : 40200032
Element Version : 2.0.3 [40200032] (F-836a1462-2022-03-07 12:38:20 +0100)
SDK Version : 1.3.12 (836a1462)
Phone : Core-X4 NEO (2022031712 11 REL)
Memory statuses
usedSize 94 MB
freeSize 12 MB
totalSize 106 MB
Thread: main, Exception: java.lang.StringIndexOutOfBoundsException: length=161; index=-1
at java.lang.String.substring(String.java:2057)
at android.text.SpannableStringInternal.<init>(SpannableStringInternal.java:35)
at android.text.SpannableString.<init>(SpannableString.java:48)
at android.text.SpannableString.subSequence(SpannableString.java:68)
at me.saket.bettermovementmethod.BetterLinkMovementMethod$ClickableSpanWithText.ofSpan(BetterLinkMovementMethod.java:6)
at me.saket.bettermovementmethod.BetterLinkMovementMethod$LongPressTimer.run(BetterLinkMovementMethod.java:7)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7705)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit..java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; Core-X4 NEO Build/RKQ1.210614.002; SAID 2318faf75d800e2b; Flavour FDroid; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (F-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "develop11"
can_contact: "false"
default_app_language: "fr_FR"
device: "Core-X4 NEO"
device_id: "RSLICGUTLU"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30) 2022031712-REL"
server_version: "undefined"
theme: "system"

**Comment by appndigital** [comment]
Reference in Element  : 
https://github.com/vector-im/element-android/issues/4519
